---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api-d-l # match template metadata labels
  template:
    metadata:
      labels:
        app: stock-api-d-l
    spec:
      containers:
      - name: stock-api-c
        image: ysurendrak/sure-py-stock-services:latest
        ports:
        - name: api
          containerPort: 5000 # Should match with docer expose port
        resources:
          requests:
            memory: 56Mi
            cpu: 50m
          limits:
            memory: 56Mi
            cpu: 50m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general
      # tolerations:
      # - key: team
      #   operator: Equal
      #   value: devops
      #   effect: NoSchedule