---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
 name: stock-api-ingress
 labels:
   app: stock-api-ingress
   tier: backend
   environment: dev
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
  - host: stock-api.info
    http:
      paths:
      - backend:
          serviceName: stock-api-np-s
          servicePort: 80
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: stock-api-np-s
spec:
  type: NodePort # adding a cluster-wide port on top of ClusterIP. exposes the service on each Node’s IP at a static port (the NodePort)
  selector:
    app: stock-api-d-l # Should match matchLabels of deploy for outbound
  ports:
    - name: http
      protocol: TCP
      port: 5500
      targetPort: api # Should match ports of deploy for inbound
      nodePort: 30001 # 30000-32767, Optional field
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api-d-l # match template `labels`
  template:
    metadata:
      labels:
        app: stock-api-d-l
    spec:
      containers:
      - name: stock-api-c
        image: ysurendrak/sure-py-stock-services:latest
        ports:
        - name: api
          containerPort: 5000
        resources:
          requests:
            memory: 56Mi
            cpu: 50m
          limits:
            memory: 56Mi
            cpu: 50m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general
      # tolerations:
      # - key: team
      #   operator: Equal
      #   value: devops
      #   effect: NoSchedule